version: "3.8"
services:

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saline-front
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - acpSymfony

volumes:
  node_modules:

networks:
  acpSymfony:
    driver: bridge
